name: Update Repository Packages

on:
  push:
    branches: [ main ]  # Change to your default branch if different

jobs:
  update-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for pushing changes back

      - name: Make update.sh executable
        run: chmod +x update.sh

      - name: Run update.sh
        run: ./update.sh

      - name: Commit and push package files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Packages Packages.bz2 Packages.gz
          git diff --quiet && git diff --staged --quiet || git commit -m "Update package indexes [skip ci]"
          git push